version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'tracking-db'
      MYSQL_USER: 'trackingrw'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - backend
volumes:
  my-db:
networks:
  backend: