FROM 	mcr.microsoft.com/devcontainers/base:ubuntu

RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update \
  && apt-get install -yq \
    curl \
    git \
    libdevel-patchperl-perl \
    libgd-dev uuid-dev \
    libgd-text-perl \
    libmodule-runtime-perl \
    libmysqlclient-dev \
    mysql-client